### ISSUE TITLE
SpringAnnotationInteceptor 捕获异常导致事务被错误提交

### ISSUE THREAD

**Issue by dong4j** [caijianying/Service-invocation-monitor#3]
SpringAnnotationInteceptor 64 行因为捕获了异常且没有抛出, 导致基于事务这类需要异常来判断进行其他操作的逻辑无法正常进行, 因此这里最好改为在 finally 中输出你的错误信息, 或者不输出也行.

**Comment by caijianying** [comment]
此问题已经解决了，不再捕获外部应用产生的异常。最新发布版本1.0.7可以验证下哈

**Comment by caijianying** [comment]
此问题已经解决了，不再捕获外部应用产生的异常。最新发布版本1.0.7可以验证下哈
