### ISSUE TITLE
spring project run test is error

### ISSUE THREAD

**Issue by hexonal** [caijianying/Service-invocation-monitor#5]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/38680988/221339833-1beda47c-8790-4cac-9f6d-a1de091175c3.png">

**Comment by caijianying** [comment]
不是SpringBoot项目吗，下载插件最新版本试试？

**Comment by caijianying** [comment]
若还有问题，可以把关键代码贴出来，我后续验证哈

**Comment by bwgqeyim** [comment]
我也是这个问题，一模一样，已经是最新版插件了

**Comment by caijianying** [comment]
好的，问题收到，请问是springboot项目吗，如果是的话，请给一下版本

**Comment by hexonal** [comment]
不需要指定的版本,这个 bugfix 是由于执行 test 导致的

**Comment by caijianying** [comment]
哦，执行test吗，我知道了。感谢支持！计划在下个版本修复！
